name: Compile LaTex
on: [push]
permissions:
  contents: write

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: JSONResume Convert
  # You may pin to the exact commit or the version.
  # uses: rvdwegen/action-jsonresume-convert@1a3bfb03c607b72281a44b481c74ac41bf0e2c35
        uses: rvdwegen/action-jsonresume-convert@latest
        with:
          theme: flat
          resume_filepath: resume.json
          output_html_filepath: index.html
          output_pdf_filepath: resume.pdf
      - name: Add to Repo
        run: |
          git config --global user.name "Justin Lopato"
          git config --global user.email "justin@lopato.org"
          git add index.html resume.pdf
          git commit -m "compiled resume.json"
          git push
                
                
            
