name: Compile LaTex
on: [push]

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            l3build latex latex-bin luatex latex-bin-dev scheme-basic
      - name: Use TeX Live
        run: pdflatex resume.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: resume.pdf
          path: resume.pdf
          overwrite: true
                
                
            
