name: Compile LaTex
on: [push]
permissions:
  contents: write

jobs:
  texlive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            l3build latex latex-bin luatex latex-bin-dev scheme-basic
      - name: Use TeX Live
        run: pdflatex resume.tex
      - name: Add to Repo
        run: |
          git config --global user.name "Justin Lopato"
          git config --global user.email "justin@lopato.org"
          git add resume.pdf
          git commit -m "compiled resume.pdf"
          git push
                
                
            
